// pub const TICK_PER_SECOND: usize = 60;
pub const TICK_MOVE_DOWN_INPUT_PRESSED_TRIGGER: i32 = 3;
pub const TICK_MOVE_DOWN_INPUT_PRESSED_RESET: i32 = 1;
pub const TICK_MOVE_DOWN_INPUT_RELEASED_RESET: i32 = 0;

pub const TICK_DAS_PRESSED_TRIGGER: i32 = 16;
pub const TICK_DAS_PRESSED_RESET: i32 = 10;
pub const TICK_DAS_RELEASED_RESET: i32 = 0;
