name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Zip Artifact
        run: |
          New-Item -Path ./target/release/tetris -ItemType Directory
          Copy-Item -Path ./assets -Destination ./target/release/tetris -Recurse
          Copy-Item -Path ./target/release/tetris.exe -Destination ./target/release/tetris
          Compress-Archive -Path ./target/release/tetris -DestinationPath ./target/release/tetris-win-x64-${{ github.ref_name }}.zip

      - name: Upload Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/release/tetris-win-x64-${{ github.ref_name }}.zip
          asset_name: tetris-win-x64-${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: false
          make_latest: false
          body: "TODO:"
